# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a96aebda1e70d313ba651c925a9ffff387f6f5f7113fb375f882bf63dbb581b518ce1c9fa04e8c09941bbe11b00af4dfc3b7d2aee03e542f2203b0a25c85336

test:
  secret_key_base: 360273d33546e985e3c3ce87167155210ac2b9916dc87d5a06d938ab350dd34864d62bd0ec1a226c7969f29597423ff9518ce1a9c3a22b66774b9f751574a8c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
